### ISSUE TITLE
QBO API returning validation errors for SalesReceipt create

### ISSUE THREAD

**Issue by rbonestell** [IntuitDeveloper/SampleApp-CRUD-.Net#17]
Using example code from this and other Intuit repos, the SDK builds what seems to be a valid request with all required fields, then the API causes the SDK to throw a BadRequest exception:

        private static SalesReceipt CreateSalesReceipt(ServiceContext context)
        {
            SalesReceipt salesReceipt = new SalesReceipt();

            List<Line> lineList = new List<Line>();
            Line line = new Line
            {
                Description = "POS Sale",
                Amount = new Decimal(100.00),
                DetailType = LineDetailTypeEnum.SalesItemLineDetail,
            };
            
            line.AnyIntuitObject = new SalesItemLineDetail()
            {
                Qty = 1
            };
            
            lineList.Add(line);
            salesReceipt.Line = lineList.ToArray();

            return salesReceipt;
        }

Results in this exception:
{"Validation Exception was thrown.Details:Required parameter Line.DetailType is missing in the request."}

You can see Line.DetailType is not missing...

**Comment by nimisha84** [comment]
Add this line too- line.DetailTypeSpecified = true;

Our sdk has many properties where fields ending in 'specified' need to be set to true so that the corresponding property gets added in the request.
Enable logging in your code to see what request was generated. You will see that after using specified property, the corresponding element was added in the request.

Logging-
To manage exception handling in your code:

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

If you still do not see error details, enable logging in code using these three lines:

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true;
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.
